blueprint:
  name: Scene Control Dial (ZHA) + Double & Long Press
  description: |
    Control actions from Zigbee scene dial with support for dial turns, button presses, double press and long press on center button.
  domain: automation
  input:
    centre_press_single_action:
      name: Centre Button – Single Press
      default: []
      selector:
        action: {}
    centre_press_double_action:
      name: Centre Button – Double Press
      default: []
      selector:
        action: {}
    centre_press_long_action:
      name: Centre Button – Long Press
      default: []
      selector:
        action: {}
    # You can add others here like before (button_1_action, dial_clockwise_action, etc.)

trigger:
  - platform: event
    event_type: zha_event

variables:
  ieee: "cc:86:ec:ff:fe:11:2f:63"
  trigger_data: "{{ trigger.event.data }}"
  now_ts: "{{ now().timestamp() }}"
  last_press_ts: "{{ (states('input_datetime.scene_control_last_press') | as_datetime).timestamp() if states('input_datetime.scene_control_last_press') else 0 }}"
  time_since_last_press: "{{ now_ts - last_press_ts }}"

condition:
  - condition: template
    value_template: "{{ trigger.event.data.device_ieee == ieee }}"

action:
  - choose:
      # ============ Centre Button Press Logic ============
      - conditions:
          - "{{ trigger_data.cluster_id == 6 }}"
          - "{{ trigger_data.command in ['on', 'off'] }}"
        sequence:
          - service: input_datetime.set_datetime
            data:
              entity_id: input_datetime.scene_control_hold_start
              timestamp: "{{ now().timestamp() }}"
          - delay:
              milliseconds: 800
          - choose:
              # If time since hold start is > 0.8s, it's a long press
              - conditions:
                  - condition: template
                    value_template: >
                      {{ now().timestamp() - (states('input_datetime.scene_control_hold_start') | as_datetime).timestamp() > 0.7 }}
                sequence: !input centre_press_long_action
              # If pressed again within 500ms, it's a double
              - conditions:
                  - condition: template
                    value_template: "{{ time_since_last_press < 0.5 }}"
                sequence: !input centre_press_double_action
              # Otherwise, it's a single
              - conditions:
                  - condition: template
                    value_template: "{{ time_since_last_press >= 0.5 }}"
                sequence: !input centre_press_single_action

          - service: input_datetime.set_datetime
            data:
              entity_id: input_datetime.scene_control_last_press
              timestamp: "{{ now().timestamp() }}"
