blueprint:
  name: Sunricher HK-ZRC-K5 - Button Actions
  description: Handle short press events from the Sunricher HK-ZRC-K5 / RS-TL 5-button remote via ZHA.
  domain: automation
  input:
    remote_device:
      name: Remote device
      description: Select the Sunricher device.
      selector:
        device:
          integration: zha
    button_1_action:
      name: Button 1
      description: Action for Button 1 short press
      default: []
      selector:
        action: {}
    button_2_action:
      name: Button 2
      description: Action for Button 2 short press
      default: []
      selector:
        action: {}
    button_3_action:
      name: Button 3
      description: Action for Button 3 short press
      default: []
      selector:
        action: {}
    button_4_action:
      name: Button 4
      description: Action for Button 4 short press
      default: []
      selector:
        action: {}
    button_5_action:
      name: Button 5
      description: Action for Button 5 short press
      default: []
      selector:
        action: {}

trigger:
  - platform: event
    event_type: zha_event

condition:
  - condition: template
    value_template: "{{ trigger.event.data.device_id == device_id(remote_device) }}"

action:
  - variables:
      button: "{{ trigger.event.data.command }}"
  - choose:
      - conditions: "{{ button == 'button_1_press' }}"
        sequence: !input button_1_action
      - conditions: "{{ button == 'button_2_press' }}"
        sequence: !input button_2_action
      - conditions: "{{ button == 'button_3_press' }}"
        sequence: !input button_3_action
      - conditions: "{{ button == 'button_4_press' }}"
        sequence: !input button_4_action
      - conditions: "{{ button == 'button_5_press' }}"
        sequence: !input button_5_action
